# Generated by Django 4.2.6 on 2023-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_sitesettings_title_suffix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="title_suffix",
            field=models.CharField(
                default=" | The Watermelon Studio Shop",
                help_text='The suffix for the title meta tag e.g. " | The Watermelon Studio Shop"',
                max_length=255,
                verbose_name="Title suffix",
            ),
        ),
    ]
