# Generated by Django 4.2.6 on 2023-10-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0003_homepage_body_homepage_featured_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_footer_link",
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_footer_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page to link to for the Footer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Hero Footer page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_footer_url",
            field=models.URLField(
                blank=True,
                help_text="Choose a URL to link to for the Footer. Ignored if footer page is set.",
                null=True,
                verbose_name="Hero Footer link",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="featured_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Featured section for the homepage. Will display up to three child items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Featured section",
            ),
        ),
    ]
