# Generated by Django 4.2.3 on 2023-09-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_shoppage_shopcategorypage_productpage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shopcategorypage",
            options={},
        ),
    ]
