# Generated by Django 4.2.3 on 2023-09-02 12:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_product_body_product_image_product_introduction_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopcategorypage",
            name="category",
        ),
        migrations.RemoveField(
            model_name="shopcategorypage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="product",
            name="body",
        ),
        migrations.RemoveField(
            model_name="product",
            name="introduction",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Description of the product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="index",
            field=models.PositiveIntegerField(
                default=100, help_text="Used for ordering products on the category page"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="live",
            field=models.BooleanField(
                default=True, help_text="Display this product in the shop"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="body",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional text to describe the category",
                verbose_name="Page body",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="index",
            field=models.PositiveIntegerField(
                default=100, help_text="Used for ordering categories on the shop page"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="live",
            field=models.BooleanField(
                default=True, help_text="Display this category in the shop"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="live",
            field=models.BooleanField(
                default=True, help_text="Display this product variant in the shop"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.productcategory",
            ),
        ),
        migrations.DeleteModel(
            name="ProductItem",
        ),
        migrations.DeleteModel(
            name="ShopCategoryPage",
        ),
    ]
