# Generated by Django 4.2.4 on 2023-09-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("shop", "0007_remove_shopcategorypage_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Images can be added to product and/or product variants, all will be displayed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="name",
            field=models.CharField(
                help_text="\n            A variant represents a single item that can be ordered/purchased. E.g.\n            if the product is 'T-shirt', a variant might be \"Black, Small\".  A product\n            'Pen' might have variants 'Single', 'Pack of 5', 'Pack of 10'\n        ",
                max_length=255,
                verbose_name="Variant name",
            ),
        ),
    ]
