# Generated by Django 4.2.4 on 2023-09-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_shopsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(default="foo", max_length=255),
            preserve_default=False,
        ),
    ]
