# Generated by Django 4.2.6 on 2023-10-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_order_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
