# Generated by Django 4.2.6 on 2023-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_order_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="stock",
            field=models.IntegerField(
                default=1, help_text="Quantity of this item currently in stock"
            ),
        ),
    ]
