# Generated by Django 4.2.6 on 2023-10-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_productvariant_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="\n            A variant represents a single item that can be ordered/purchased. E.g.\n            A product 'Pen' might have variants 'Single', 'Pack of 5', 'Pack of 10'.\n            Can be left blank if there is only one variant for this product, or if it\n            only varies by colour and/or size. \n            e.g. \n            - Product Mug: one product variant, with no name, colour or size specifications.\n            - Product T-shirt: size/colour variants with no separate name (e.g. black,S)\n            - Product Hoodie: variants with name \"Men's Hoodie\", \"Women's Hoodie\", each \n              with size and colour options\n        ",
                max_length=255,
                null=True,
                verbose_name="Variant name",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="colour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.colour",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="size",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="shop.size"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("name", "colour", "size")},
        ),
    ]
