# Generated by Django 4.2.6 on 2023-10-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_colour_size_alter_productvariant_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="colour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.colour",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.size",
            ),
        ),
    ]
