# Generated by Django 4.2.6 on 2023-10-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0015_rename_name_productvariant_variant_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="shipping_method",
            field=models.CharField(
                choices=[("collect", "Collect in store"), ("deliver", "delivery")],
                default="collect",
            ),
        ),
    ]
