# Generated by Django 4.2.6 on 2023-10-15 14:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_alter_order_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Default price for this product. Can be overridden by setting price on individual variants.",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="basket",
            name="shipping_method",
            field=models.CharField(
                choices=[("collect", "Collect in store"), ("deliver", "Delivery")],
                default="collect",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[("collect", "Collect in store"), ("deliver", "Delivery")],
                default="collect",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave blank to use default product price.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="shop.product",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="variant_name",
            field=models.CharField(
                blank=True,
                help_text="Can be left blank if there is only one variant for this product.",
                max_length=255,
                null=True,
                verbose_name="Variant name",
            ),
        ),
    ]
