# Generated by Django 4.2.6 on 2023-10-16 08:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("shop", "0023_delete_colour_delete_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Optional text to describe the category",
                        verbose_name="Page body",
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Used for ordering categories on the shop page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AddField(
            model_name="product",
            name="category_page",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_page",
                to="shop.categorypage",
            ),
        ),
    ]
