# Generated by Django 4.2.6 on 2023-10-16 12:57

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0024_categorypage_product_category_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="category_page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_products",
                to="shop.categorypage",
            ),
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
    ]
