# Generated by Django 4.2.6 on 2023-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0025_remove_product_category_alter_product_category_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="timeout",
            field=models.DateTimeField(null=True),
        ),
    ]
