# Generated by Django 4.2.6 on 2024-01-05 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0026_basket_timeout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="categorypage",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.CreateModel(
            name="SaleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
                (
                    "sale",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.sale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.categorypage",
                    ),
                ),
                (
                    "sale",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="shop.sale",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="start_before_end_constraint",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saleproduct",
            unique_together={("sale", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="salecategory",
            unique_together={("sale", "category")},
        ),
    ]
