# Generated by Django 4.2.6 on 2024-01-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0027_sale_alter_categorypage_options_saleproduct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="banner_content",
            field=models.TextField(
                blank=True,
                default="Discounts available across the shop.",
                help_text="Optional content to be shown in a banner on all shop pages when sale is active",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="banner_include_end",
            field=models.BooleanField(
                default=False,
                help_text="Include end date in banner (displayed as 'Sale ends on dd-mmm-yyyy at HH:MM')",
                verbose_name="Include end date in banner",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="banner_title",
            field=models.CharField(
                blank=True,
                default="Sale now on!",
                help_text="Optional title to be shown in a banner on all shop pages when sale is active",
                null=True,
            ),
        ),
    ]
